CREATE TABLE IF NOT EXISTS DIM_STATION (
    -- TODO not null a las que aparecen en informes
    ID UNSIGNED_LONG NOT NULL,
    LONGITUDE UNSIGNED_DOUBLE,
    LATITUDE UNSIGNED_DOUBLE,
    HEIGH UNSIGNED_LONG,
    VARCHAR DISTRICT,
    VARCHAR NEIGHBORHOOD,
    VARCHAR ZIP_CODE,
    VARCHAR ADDRESS);