package org.collprod.bicingbcn.ingestion.commons;

import com.google.common.base.Optional;

/**
 * Convenience class for MutableObjects that contain an Optional value
 * */
public class MutableOptionalObject<V> extends MutableObject<Optional<V>> {

	// Generated by Eclipse
	private static final long serialVersionUID = -3188469822473893679L;

	/**
	 * Create a mutable value containing an optional absent value
	 * */
	@SuppressWarnings("unchecked")
	public MutableOptionalObject() {
		this((Optional<V>)Optional.absent());
	}
	
	/**
	 * Create a mutable value containing an optional present value with 
	 * the value specified 
	 * */
	public MutableOptionalObject(V value) {
		super(Optional.of(value));
	}
	
	/**
	 * Create a mutable value containing the optional value specified
	 * */
	public MutableOptionalObject(Optional<V> value) {
		super(value);
	}
	
	/**
	 * Set the value to an optional present value with the value specified 
	 * Cannot override MutableObject.setValue as generics overlap
	 * 
	 * @param value to be set
	 * */
	public void setPresentValue(V value) {
		super.set(Optional.of(value));
	}
		
	/**
	 * Set the value to an optional absent value
	 * */
	@SuppressWarnings("unchecked")
	public void setAbsent() {
		super.set((Optional<V>)Optional.absent());
	}
	
	@Override
	public String toString() {
		// mimicking implementation synthesized for an 
		// AutoValue (https://github.com/google/auto/tree/master/value)
		return "MutableOptionalObject{"
				+ "value=" + this.get()
				+ "}";
	}
	
	public static void main (String [] a) {
		MutableOptionalObject<String> mutableString = new MutableOptionalObject<String>();
		System.out.println(mutableString);
		mutableString.set(Optional.of("hola"));
		System.out.println(mutableString);
		mutableString.setPresentValue("adios");
		System.out.println(mutableString);
		mutableString.setAbsent();
		System.out.println(mutableString);
		mutableString.setPresentValue("ey");
		System.out.println(mutableString);
		
		mutableString = new MutableOptionalObject<String>("hola");
		System.out.println(mutableString);
		
		Optional<String> absentString = Optional.absent();
		mutableString = new MutableOptionalObject<String>(absentString);
		System.out.println(mutableString);
		
		mutableString = new MutableOptionalObject<String>(Optional.of("hola"));
		System.out.println(mutableString);
	
		mutableString = new MutableOptionalObject<String>(Optional.of("hola"));
		System.out.println(mutableString.equals(new MutableObject<String>("hola")));
		

		
	}
}
